import { mkdirSync, writeFileSync, existsSync, statSync, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HOME_URL = (id) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/${id}.png`
const FALLBACK_URL = (id) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`

const TRAINER_SPECIES = {
  'trainer-001': 'eevee',
  'trainer-002': 'starmie',
  'trainer-003': 'onix',
  'trainer-004': 'vileplume',
  'trainer-005': 'alakazam',
  'trainer-006': 'arcanine',
  'trainer-007': 'mewtwo',
  'trainer-008': 'lapras',
  'trainer-009': 'machamp',
  'trainer-010': 'gengar',
}

const SPECIES_ALIASES = {
  deoxys: 'deoxys-normal',
}

const PROJECT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const CARDS_PATH = join(PROJECT_ROOT, 'web', 'src', 'data', 'cards.ts')
const OUT_DIR = join(PROJECT_ROOT, 'web', 'public', 'assets', 'pokemon')
const MANIFEST_PATH = join(PROJECT_ROOT, 'web', 'src', 'data', 'asset-sources.ts')

const TIMEOUT_MS = 30_000
const MAX_TRIES = 2

function parseCards() {
  const source = readFile(CARDS_PATH)
  const pairs = []
  const pattern = /defineCard\(\s*\d+\s*,\s*'(?:tier|noble)-[^']*'\s*,\s*'([^']+)'\s*,\s*'((?:pokemon|trainer)-\d+)'/g
  for (const match of source.matchAll(pattern)) {
    pairs.push({ name: match[1], imageKey: match[2] })
  }
  return pairs
}

function readFile(path) {
  try {
    return readFileSync(path, 'utf8')
  } catch (error) {
    console.error(`Cannot read ${path}: ${error.message}`)
    process.exit(1)
  }
}

function fetchWithTimeout(url, tries = MAX_TRIES) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS)
  return fetch(url, { signal: controller.signal })
    .catch((error) => {
      if (tries > 1) {
        return fetchWithTimeout(url, tries - 1)
      }
      throw error
    })
    .finally(() => clearTimeout(timer))
}

async function resolveId(name) {
  const candidates = [name, SPECIES_ALIASES[name.toLowerCase()], name.toLowerCase()]
  const seen = new Set()
  let lastError
  for (const candidate of candidates) {
    if (candidate === undefined || seen.has(candidate)) {
      continue
    }
    seen.add(candidate)
    try {
      const response = await fetchWithTimeout(`https://pokeapi.co/api/v2/pokemon/${candidate}`)
      if (response.ok) {
        const data = await response.json()
        return data.id
      }
      lastError = new Error(`PokéAPI returned ${response.status} for "${candidate}"`)
    } catch (error) {
      lastError = error
    }
  }
  throw lastError ?? new Error(`No candidate resolved for "${name}"`)
}

async function downloadImage(url, destination) {
  const response = await fetchWithTimeout(url)
  if (!response.ok) {
    return { ok: false, reason: `HTTP ${response.status}` }
  }
  const buffer = Buffer.from(await response.arrayBuffer())
  if (buffer.length === 0) {
    return { ok: false, reason: 'empty response' }
  }
  writeFileSync(destination, buffer)
  return { ok: true, bytes: buffer.length }
}

async function ensureImage({ imageKey, name, id, fileName }) {
  const destination = join(OUT_DIR, fileName)
  const sourceUrl = HOME_URL(id)

  if (existsSync(destination) && statSync(destination).size > 0) {
    return { imageKey, name, id, sourceUrl, status: 'kept' }
  }

  const attempts = [
    [HOME_URL(id), HOME_URL(id)],
    [FALLBACK_URL(id), FALLBACK_URL(id)],
  ]

  for (const [url] of attempts) {
    try {
      const result = await downloadImage(url, destination)
      if (result.ok) {
        return { imageKey, name, id, sourceUrl: url, status: 'downloaded', bytes: result.bytes }
      }
    } catch {
      // try next URL
    }
  }

  return { imageKey, name, id, sourceUrl, status: 'failed' }
}

function writeManifest(entries) {
  const lines = entries.map(({ imageKey, sourceUrl }) => `  '${imageKey}': '${sourceUrl}',`)
  const content = [
    '// Auto-generated by web/scripts/download-assets.mjs',
    '// Maps every card/trainer imageKey to the exact artwork URL it was downloaded from.',
    'export const ASSET_SOURCES: Record<string, string> = {',
    ...lines,
    '}',
    '',
  ].join('\n')
  writeFileSync(MANIFEST_PATH, content)
}

async function main() {
  const entries = [...parseCards(), ...Object.entries(TRAINER_SPECIES).map(([imageKey, name]) => ({ imageKey, name }))]

  if (entries.length !== 100) {
    console.error(`Expected 100 asset entries, found ${entries.length}`)
    process.exit(1)
  }

  mkdirSync(OUT_DIR, { recursive: true })

  const idCache = new Map()
  const results = []

  for (const entry of entries) {
    const fileName = `${entry.imageKey}.png`
    let id = idCache.get(entry.name)
    if (id === undefined) {
      try {
        id = await resolveId(entry.name)
        idCache.set(entry.name, id)
      } catch (error) {
        console.error(`FAILED  ${entry.imageKey} (${entry.name}): ${error.message}`)
        results.push({ ...entry, id: null, sourceUrl: '', status: 'failed' })
        continue
      }
    }
    const result = await ensureImage({ ...entry, id, fileName })
    results.push(result)
    const label = `${result.imageKey} (${entry.name})`
    if (result.status === 'failed') {
      console.error(`FAILED  ${label}`)
    } else {
      console.log(`OK      ${label} -> ${fileName}`)
    }
  }

  writeManifest(results)

  const failed = results.filter((result) => result.status === 'failed')
  const downloaded = results.filter((result) => result.status === 'downloaded')
  const kept = results.filter((result) => result.status === 'kept')
  const totalBytes = results
    .filter((result) => result.status !== 'failed')
    .reduce((sum, result) => sum + statSync(join(OUT_DIR, `${result.imageKey}.png`)).size, 0)

  console.log('')
  console.log(`Summary: ${results.length - failed.length}/${results.length} images present (${downloaded.length} downloaded, ${kept.length} kept existing)`)
  console.log(`Total size: ${(totalBytes / 1024).toFixed(1)} KiB`)
  if (failed.length > 0) {
    console.error(`Failures (${failed.length}):`)
    for (const result of failed) {
      console.error(`  ${result.imageKey} ${result.name} -> ${result.sourceUrl}`)
    }
    process.exitCode = 1
  }
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
